services:
  mysql:
    image: mysql:8.0
    container_name: todo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo123
    ports:
      - "3306:3306"
    volumes:
      - todo_mysql_data:/var/lib/mysql
    restart: always

volumes:
  todo_mysql_data: 
